/**
 * Canonical source coordinates for HT-PD-RD-V1.
 * These are non-secret coordinates only. They are NOT deployment proof.
 */
const RD_CANONICAL = Object.freeze({
  REPOSITORY: 'Hai-hatien/hatien-product-rd',
  BRANCH: 'backend/v1.3-hardening',
  SOURCE_VERSION: '1.3.3-worker-v1',
  APPS_SCRIPT_ID: '1TGVEpC82jSws4y6lzl2vHSZ8Z8H0dkHhUFLY5_oPaSdCbY7e4knbqsfL',
  EXISTING_DEPLOYMENT_ID: 'AKfycbyfMvQKqkRD7NMHIE2S9Hy-8YdA02pwNLR70L62N11L3b4rdHM7yxBLzfWkTCtoO4Sy',
  EXISTING_WEB_APP_URL: 'https://script.google.com/a/macros/hatiencorp.vn/s/AKfycbyfMvQKqkRD7NMHIE2S9Hy-8YdA02pwNLR70L62N11L3b4rdHM7yxBLzfWkTCtoO4Sy/exec',
  DEPLOYMENT_STATE: 'COORDINATE_KNOWN_NOT_CANONICAL_DEPLOY_PROOF',
  RUNTIME_PROVIDER: 'GEMINI',
  LEGACY_OPENAI_STATE: 'RETIRED_NOT_USED',
  CANDIDATE_SHEET: '21_RD_Candidates',
  BACKEND_READY: false
});

const RD_CANDIDATE_HEADERS = Object.freeze([
  'RD_CANDIDATE_ID', 'CANDIDATE_TITLE', 'TARGET_PRODUCT', 'TARGET_MARKET',
  'CUSTOMER_SEGMENT', 'PAIN_SIGNAL', 'OPPORTUNITY_SUMMARY', 'SOURCE_SIGNAL_IDS',
  'SOURCE_URLS', 'PROVENANCE_JSON', 'DEDUP_KEY', 'DEDUP_STATUS',
  'CANDIDATE_STATUS', 'CONFIDENCE', 'CREATED_AT', 'CREATED_BY', 'LAST_SEEN_AT',
  'RD_REQUEST_ID', 'DECISION_STATUS', 'NOTES'
]);

function candidateSheetName_() {
  return RD_CANONICAL.CANDIDATE_SHEET;
}
